# fly.toml file generated for nameless-smoke-51 on 2023-03-31T23:10:32+03:00

app = "nameless-smoke-51"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "waw"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
